{
    "_Name": "TimeSheetEditAction",
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"Target":
	{
		"EntitySet" : "CatsTimesheets",
        "Service" : "/SAPAssetManager/Services/AssetManager.service",
        "ReadLink": "{@odata.readLink}"
	},
	"Properties":
	{
		"Hours": 0.0,
        "StartTime": "00:00:00",
        "EndTime": "00:00:00"
    },
    "Headers": {
        "OfflineOData.TransactionID": "#Property:Counter"
	},
	"OnSuccess" : "/SAPAssetManager/Rules/TimeSheets/TimeSheetEntrySuccessMessage.js",
	"OnFailure": "/SAPAssetManager/Actions/TimeSheets/TimeSheetEntryFailureMessage.action"
}